apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chaos-demo
  template:
    metadata:
      labels:
        app: chaos-demo
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: chaos-demo-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-demo-html
  namespace: default
data:
  index.html: |
    <html>
    <head><title>Chaos Edge Live</title></head>
    <body style="font-family: monospace; padding: 50px;">
      <h1>Chaos Edge Platform</h1>
      <p>CloudFront to NLB to NGINX Ingress to Pod</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: chaos-demo
  namespace: default
spec:
  selector:
    app: chaos-demo
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chaos-demo
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chaos-demo
            port:
              number: 80